// POST /api/auth/verify
//
// The Firebase ↔ Supabase bridge. Called after the client successfully
// completes Firebase phone OTP. Does three things:
//   1. Verifies the Firebase ID token server-side (can't be faked)
//   2. Looks up or creates the user in our Supabase users table
//   3. Mints a Supabase-compatible JWT and sets it as an httpOnly cookie
//
// After this returns, the client can use Supabase directly (realtime, queries)
// because the cookie carries a JWT that Supabase's RLS trusts.

import { NextResponse } from 'next/server'
import { SignJWT } from 'jose'
import { firebaseAdmin } from '@/lib/firebase/admin'
import { createServiceClient } from '@/lib/supabase/server'

// Session length: 7 days. User re-auths after this. Adjust as needed.
const SESSION_DURATION_SECONDS = 60 * 60 * 24 * 7

export async function POST(req: Request) {
  const { idToken } = await req.json() as { idToken?: string }

  if (!idToken) {
    return NextResponse.json({ error: 'idToken required' }, { status: 400 })
  }

  // ── 1. Verify Firebase token ───────────────────────────────────────────────
  let phoneNumber: string
  try {
    const decoded = await firebaseAdmin.verifyIdToken(idToken)
    if (!decoded.phone_number) {
      return NextResponse.json({ error: 'No phone number in token' }, { status: 400 })
    }
    phoneNumber = decoded.phone_number  // E.164 format, e.g. '+15551234567'
  } catch {
    return NextResponse.json({ error: 'Invalid Firebase token' }, { status: 401 })
  }

  // ── 2. Look up or create the Supabase user ────────────────────────────────
  const supabase = createServiceClient()

  let userId: string
  let isNewUser: boolean

  const { data: existing } = await supabase
    .from('users')
    .select('id')
    .eq('phone', phoneNumber)
    .maybeSingle() as { data: { id: string } | null }

  if (existing) {
    userId = existing.id
    isNewUser = false
  } else {
    // New user — create the row. referral_code is auto-generated by the DB default.
    const { data: created, error } = await supabase
      .from('users')
      .insert({ phone: phoneNumber })
      .select('id')
      .single()

    if (error || !created) {
      console.error('Failed to create user:', error)
      return NextResponse.json({ error: 'Failed to create user' }, { status: 500 })
    }

    userId = created.id
    isNewUser = true
  }

  // ── 3. Mint a Supabase-compatible JWT ────────────────────────────────────
  // Supabase reads `sub` as auth.uid() in RLS policies.
  // `role: 'authenticated'` is required for RLS to treat this as a signed-in user.
  const secret = new TextEncoder().encode(process.env.SUPABASE_JWT_SECRET!)

  const token = await new SignJWT({
    sub:  userId,
    role: 'authenticated',
    phone: phoneNumber,
  })
    .setProtectedHeader({ alg: 'HS256' })
    .setIssuedAt()
    .setExpirationTime(`${SESSION_DURATION_SECONDS}s`)
    .sign(secret)

  // ── 4. Set cookie and return ───────────────────────────────────────────────
  const response = NextResponse.json({ isNewUser })

  response.cookies.set('mooves-token', token, {
    httpOnly: true,
    secure: process.env.NODE_ENV === 'production',
    sameSite: 'lax',
    maxAge: SESSION_DURATION_SECONDS,
    path: '/',
  })

  return response
}
